gestionProduit/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views 
from . import views
from gestionVente.views import recherche_produit as recherche_produit
from django.contrib import admin


app_name='gestionProduit'

urlpatterns = [
    path('', views.menu,name='menu'),
    path('gestion_produits', views.gestion_produits,name='produit'),
    path('affichageProduit', views.affichageProduit, name='affichage_produit'),
    path('delete/<int:id>', views.delete,name='delete'),
    path('update/<int:id>', views.update, name='update'),
    path('page1', views.page1, name='page1'), 
    path('formulaireCategorie', views.formulaireCategorie, name='formulaireCategorie'), 
    path('afficher_categories', views.afficher_categories, name='afficher_categories'),
    path('supprimer_categorie/<int:categorie_id>/', views.supprimer_categorie, name='supprimer_categorie'),
    path('recherche_produit', views.recherche_produit, name='recherche_produit'), 
    path('transactions', views.transactions, name='transactions'),
    path('validation', views.validation, name='validation'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('<int:id>/', views.ajouter_panier, name='ajouter_panier'),
    path('afficher_panier/', views.afficher_panier, name='afficher_panier'),
    path('deletePanier/', views.deletePanier, name='deletePanier'),
    path('recu/<int:transaction_id>', views.recu, name='recu'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('statistiques_json', views.statistiques_json, name='statistiques_json'),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

gestionVente/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

app_name='gestionVente'

urlpatterns = [
    path('', views.recherche_produit, name='recherche_produit'),
]

sujet2_test/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionProduit.urls')),
    path('', include('gestionVente.urls')),
]

gestionVente/models.py
from django.db import models

# Create your models here.

gestionVente/views.py
from django.shortcuts import render
from gestionProduit.models import *

def recherche_produit(request):
    terme_recherche = request.GET.get('terme_recherche', '')

    if terme_recherche:
        # Effectuez la recherche dans la base de données
        resultats = Produit.objects.filter(nom_produit__icontains=terme_recherche)
    else:
        resultats = None

    return render(request, 'rechercheProduit.html', {'resultats': resultats, 'terme_recherche': terme_recherche})

gestionVente/templates/rechercheProduit.html
{% extends 'menu.html' %}

{% block title %}Recherche d'articles{% endblock %}

{% block content %}
  <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1">
      <form method="get" action="{% url 'gestionProduit:recherche_produit' %}">
        <input name="terme_recherche" class="w-full py-4 px-6 border rounded-xl" type="text" placeholder="Rechercher un produit" value="{{ terme_recherche }}">
        <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Rechercher</button>
      </form>

      <hr class="my-6">

      <p class="font-semibold">Categories</p>

      <ul>
        {% for categorie in categories %}
          <li class="py-2 px-2 rounded-xl{% if categorie.id == categorie_id %} bg-gray-200{% endif %}">
            <a href="{% url 'gestionProduit:recherche_produit' %}?terme_recherche={{ terme_recherche }}&categorie={{ categorie.id }}">{{ categorie.nom_categorie }}</a>
          </li>
        {% endfor %}
      </ul>

      <hr class="my-6">

      <p class="font-semibold">Clear filters</p>

      <ul>
        <li><a href="{% url 'gestionProduit:recherche_produit' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
      </ul>
    </div>

    <div class="col-span-3">
      <div class="grid grid-cols-3 gap-3">
        {% for produit in resultats %}
          <div>
            <a href="{% url 'gestionProduit:detail' produit.id %}">
              <div>
                <!-- Ajoutez vos classes Tailwind pour l'image ici -->
                <img src="{{ produit.image.url }}" class="rounded-t-xl">
              </div>

              <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{ produit.nom_produit }}</h2>
                <p class="text-gray-500">Quantité: {{ produit.quantite_produit }} - Prix: {{ produit.prix }}</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}